### ISSUE TITLE
Implementation corrections

### ISSUE THREAD

**Issue by malkhalidi-atypon** [aymanmowafi92/api-throttling#1]
The request initially was about introducing a limit per IP address e.g. if two requests came from 192.168.1.23 they should affect the same limit for that counter of that specific IP.

If two requests came from unique IPs, they shouldn't affect the counters of each other.

The usage of Java data structures is preferred. The current implementation doesn't utilize the most efficient synchronization or generics to make the Queue more usable by others.

Please provide proper testing for the code and specially edge cases as there is currently no tests (unit tests, component tests) that asserts and fail if the code doesn't work.

Please as agreed provide a method a header or parameter in the requests to the service to spoof a specific IP.

**Comment by aymanmowafi92** [comment]
Thanks for your time reviewing the solution. Sure. I will work on this today after my work (in the evening) and I will consider all the mentioned points above. I am expecting to deliver this tomorrow morning enshallah. Is this OK?

**Comment by rzeineh** [comment]
That if fine

**Comment by aymanmowafi92** [comment]
Please note that all the above comments are considered and fixed. I'll be more than happy if you give me your feedback. Thanks

**Comment by aymanmowafi92** [comment]
Dear Rami and Mohammad,

Kindly note that I have made the needed corrections raised by you and
committed the changes on the github. Please let me know if you have any
questions.

https://github.com/aymanmowafi92/api-throttling

Thanks,
